apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: u9rdp66on-go
  janus-idp.io/tekton: u9rdp66on-go
  backstage.io/kubernetes-id: u9rdp66on-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u9rdp66on-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
